name: Build C++ Launcher

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    # Этот шаг принудительно включает окружение компилятора MSVC (Visual Studio) для консоли
    - name: Initialize MSVC Environment
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64

    - name: Setup CMake
      uses: jwlawson/actions-setup-cmake@v2
      with:
        cmake-version: '3.25.x'

    # Используем дефолтный для этого окружения генератор (Ninja), который 100% увидит компилятор
    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config Release

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ArbuzProtect-Launcher
        path: ${{github.workspace}}/build/Release/
