name: C/C++ Windows Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-windows:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install MinGW Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64

    - name: Download json.hpp (nlohmann/json)
      # Скачиваем стабильную версию json.hpp прямо в корень проекта
      run: |
        curl -L -o json.hpp https://github.com/nlohmann/json/releases/latest/download/json.hpp

    - name: Compile to EXE
      # Компилируем проект, теперь json.hpp лежит рядом с main.cpp
      run: |
        x86_64-w64-mingw32-g++ -O3 *.cpp -o program.exe -static -static-libgcc -static-libstdc++

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-program
        path: program.exe
